ALTER TABLE `t_collect_story` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_gift` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_gift_recorder` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_play_log` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_rewards` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_story` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_story_chapter` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `t_story_recorder` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT;