CREATE TABLE IF NOT EXISTS `t_category` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类id',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `creator` BIGINT DEFAULT NULL COMMENT '创建者',
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `updater` BIGINT DEFAULT NULL COMMENT '更新者',
    `dataVersion` INT NOT NULL DEFAULT '0' COMMENT '数据版本，每更新一次+1',
    `deleted` TINYINT DEFAULT '0' COMMENT '是否删除：0否，1是',
    `name` VARCHAR(255) NOT NULL COMMENT '分类名称',
    `weight` INT NOT NULL DEFAULT '0' COMMENT '排序权重，默认为0，权重越高排得越靠前。',
    PRIMARY KEY (`id`),
    UNIQUE KEY `name` (`name`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;